[package]
name = "sled_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = "0.11.0"
rand = "0.8.5"
serde = "1.0.197"
sled = "0.34.7"
typed-sled = "0.2.3"
